services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network
  client-service:
    build:
      context: ./client-service
      dockerfile: Dockerfile
    container_name: client_service
#    environment:
#        - SPRING_PROFILES_ACTIVE=default
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network
  billing-service:
    build:
      context: ./billing_service
      dockerfile: Dockerfile
    container_name: billing_service
    env_file:
      - .env
    ports:
      - "8081:8081"
      - "9091:9091"
    depends_on:
      - db
    networks:
      - my-network
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_broker
    ports:
      - "9092:9092"
      - "9094:9094"
    env_file:
      - .env
    networks:
        - my-network
volumes:
    postgres_data:

networks:
      my-network:
        driver: bridge


