services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_broker
    ports:
      - "9092:9092"
      - "9094:9094"
    env_file:
      - .env
    networks:
      - my-network
  client-service:
    build:
      context: ./client-service
      dockerfile: Dockerfile
    image: client-service:latest
    container_name: client_service
#    environment:
#        - SPRING_PROFILES_ACTIVE=default
    env_file:
      - .env
# close the port so that it is only accessible via the API gateway
#    ports:
#      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network
  billing-service:
    build:
      context: ./billing_service
      dockerfile: Dockerfile
    image: billing-service:latest
    container_name: billing_service
    env_file:
      - .env
    ports:
      - "8081:8081"
      - "9091:9091"
    depends_on:
      - db
    networks:
      - my-network
  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    image: analytics-service:latest
    container_name: analytics_service
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      - db
      - kafka
    networks:
      - my-network
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    container_name: auth_service
    env_file:
      - .env
    ports:
      - "8084:8084"
    depends_on:
      - db
    networks:
      - my-network
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    container_name: api_gateway
    ports:
      - "8083:8083"
    depends_on:
      - client-service
      - billing-service
      - analytics-service
    networks:
      - my-network
volumes:
    postgres_data:

networks:
      my-network:
        driver: bridge


