services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network
  client-service:
    build:
      context: ./client-service
      dockerfile: Dockerfile
    container_name: client_service
#    environment:
#        - SPRING_PROFILES_ACTIVE=default
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network
volumes:
    postgres_data:

networks:
      my-network:
        driver: bridge


