services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network
  client-service:
    build:
      context: ./client-service
      dockerfile: Dockerfile
    container_name: client_service
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - my-network
volumes:
    postgres_data:

networks:
      my-network:
        driver: bridge


