spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://host.docker.internal:8084
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0
        - id: client-service-route
          uri: http://host.docker.internal:8080
          predicates:
            - Path=/api/v1/clients/**
          filters:
            - StripPrefix=0
            - JWTValidation
        # just in case I want to route swagger docs
        - id: api-docs-client-route
          uri: http://host.docker.internal:8080
          predicates:
            - Path=/api-docs/clients
          filters:
            - RewritePath=/api-docs/clients, /v3/api-docs
        - id: api-docs-auth-route
          uri: http://host.docker.internal:8084
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth, /v3/api-docs

#just for local testing
auth:
  service:
    url: http://host.docker.internal:8084/api/v1/auth
server:
  port: 8083