spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: client-service-route
          uri: http://client-service:8080
          predicates:
            - Path=/api/v1/clients/**
          filters:
            - StripPrefix=0
        # just in case I want to route swagger docs
        - id: api-docs-client-route
          uri: http://client-service:8080
          predicates:
            - Path=/api-docs/clients
          filters:
            - RewritePath=/api-docs/clients, /v3/api-docs


server:
  port: 8083